# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: Pipeline/Variables/globals-vars.yml
  

stages:

    - stage: 'BuildSolution'
      # variables:
      #   - template: Pipeline/Variables/globals-vars.yml
      jobs:
      - template: Pipeline/dotnet-build.yml

    - stage: 'BuildOnError'
      dependsOn: BuildSolution
      condition: failed()
      variables:
        - template: Pipeline/Variables/globals-vars.yml
      jobs:
      - template: Pipeline/dotnet-error.yml


    - stage: 'Tests'
      dependsOn:
        - BuildSolution
      variables:
        - template: Pipeline/Variables/globals-vars.yml
      jobs:
      - template: Pipeline/dotnet-test.yml


    - stage: 'Publish'
      dependsOn:
        - Tests
      variables:
        - template: Pipeline/Variables/globals-vars.yml
      jobs:
      - template: Pipeline/dotnet-publish.yml
                  



