# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: Pipeline/Variables/globals-vars.yml
  

stages:
  # Build the solution.
    - stage: 'BuildSolution'
      jobs:
      - template: Pipeline/dotnet-build.yml
  # Build the projects.
    - stage: 'BuildOnError'
      dependsOn: BuildSolution
      condition: failed()
      jobs:
      - template: Pipeline/dotnet-error.yml
  # Run the tests.
    - stage: 'Tests'
      dependsOn:
        - BuildSolution
      jobs:
      - template: Pipeline/dotnet-test.yml
  # Publish Artifact
    - stage: 'Publish'
      dependsOn:
        - Tests
      jobs:
      - template: Pipeline/dotnet-publish.yml
                  



