# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  corepath: 'Pipelines/BasePipeline/EventHorizont/EventHorizont.sln'

trigger:
- develop


stages:

    - stage: 'BuildSolution'
      pool:
        vmImage: 'ubuntu-latest'
      jobs:
        - job: build
          steps:
              - task: DotNetCoreCLI@2
                displayName: 'Dotnet Restore'
                inputs:
                  command: 'restore'
                  projects: '$(corepath)'
                  configuration: $(buildConfiguration)
                
              - task: DotNetCoreCLI@2
                displayName: 'Dotnet Build'
                inputs:
                  command: 'build'
                  projects: '$(corepath)'
                  configuration: $(buildConfiguration)
                
                  



